ALTER TABLE `retur_online`
  ADD COLUMN `retur_group_id` VARCHAR(36) NULL,
  ADD COLUMN `tipe` ENUM('PENGGANTIAN_BARANG','PENGEMBALIAN_DANA') NOT NULL DEFAULT 'PENGGANTIAN_BARANG',
  ADD COLUMN `jumlah_refund` DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN `surat_jalan_awal_id` INT NULL,
  ADD COLUMN `surat_jalan_pengganti_id` INT NULL;

ALTER TABLE `surat_jalan_online`
  ADD COLUMN `jenis` ENUM('PENGIRIMAN_AWAL','PENGGANTIAN_RETUR') NOT NULL DEFAULT 'PENGIRIMAN_AWAL',
  ADD COLUMN `retur_group_id` VARCHAR(36) NULL;
